---
- include: common.yaml
  when: (role != "cluster_orchestrator")
  
- include: ambari.yaml
  when: role == "ambari"

- include: cluster_node.yaml
  when: role == "node"

- include: master.yaml
  when: role == "master"

- include: cluster.yaml
  when: role == "cluster_orchestrator"



