---
- name: reload systemd
  become: true
  command: systemctl daemon-reload

- name: start-ambari-server
  become: true
  service: 
    name: ambari-server 
    state: started
    use: service

- name: start-ambari-agent
  become: true
  service: 
    name: ambari-agent 
    state: started

